name: Inherit Labels and Assignees from Project V2 Row

on:
  issues:
    types: [opened]

permissions:
  issues: write
  repository-projects: write
  contents: read

jobs:
  inherit_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Inherit labels and assignees from Project V2
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const issueNodeId = context.payload.issue.node_id;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // 1️⃣ Use your Project V2 ID directly
            const projectId = "PVT_kwHODd007c4BEBb_"; // <-- replace with your real Project V2 ID

            // 2️⃣ Query project items with union handling
            const query = `
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            id
                          }
                        }
                        fieldValues(first: 20) {
                          nodes {
                            ... on ProjectV2ItemFieldTextValue {
                              projectField { name }
                              text
                            }
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              projectField { name }
                              name
                            }
                            ... on ProjectV2ItemFieldUserValue {
                              projectField { name }
                              users(first: 5) {
                                nodes { login }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            const projectData = await github.graphql(query, { projectId });

            // 3️⃣ Find the row that matches this issue
            const row = projectData.node.items.nodes.find(n => n.content && n.content.id === issueNodeId);
            if (!row) {
              console.log("No matching Project V2 row found for this issue. Exiting.");
              return;
            }

            // 4️⃣ Extract labels + assignees
            let labelsFromProject = [];
            let assigneesFromProject = [];

            for (const fieldNode of row.fieldValues.nodes) {
              const fieldName = fieldNode.projectField.name;

              if (fieldName === "Labels") {
                if (fieldNode.text) {
                  labelsFromProject = fieldNode.text.split(",").map(s => s.trim());
                } else if (fieldNode.name) {
                  labelsFromProject = [fieldNode.name];
                }
              }

              if (fieldName === "Assignees" && fieldNode.users) {
                assigneesFromProject = fieldNode.users.nodes.map(u => u.login);
              }
            }

            console.log("Labels to add:", labelsFromProject);
            console.log("Assignees to add:", assigneesFromProject);

            // 5️⃣ Apply labels
            if (labelsFromProject.length > 0) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: issueNumber,
                labels: labelsFromProject
              });
            }

            // 6️⃣ Apply assignees
            if (assigneesFromProject.length > 0) {
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: assigneesFromProject
              });
            }

            console.log("✅ Metadata inherited successfully!");
